### ISSUE TITLE
Can't access any websites

### ISSUE THREAD

**Issue by Hotrod006** [UseInterstellar/Interstellar#809]
When I try to look anything up, I receive this error message on-screen "RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599]."

1. Run: npn run start
2. Go to the local host website
3. Search up anything

I expected to go to the website I was looking up, which in my case was YouTube.com.

- Device: Chromebook
- OS: ChromeOS
- Browser Chrome

**Comment by IncognitoTGT** [comment]
did you make your codespace public?

**Comment by Lun-r** [comment]
You're most likely getting that error due to not setting your port to public when you run `pnpm i && pnpm start`. usually the pop-up appears in the bottom right, and will give you the option to either a. "open in browser" (which results in the error you're getting, or b. "make public" (which will have it run as intended). hope this helps

**Comment by IncognitoTGT** [comment]
stale
